#
# Copyright (c) 2020 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Logging
CONFIG_LOG=y

# Button and LED support
CONFIG_DK_LIBRARY=y

# Newlib
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=n
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_SOCKETS=y
CONFIG_POSIX_API=y

# Memory
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=1024

# Modem library
CONFIG_NRF_MODEM_LIB=y

# LTE link control
CONFIG_LTE_LINK_CONTROL=y
CONFIG_LTE_NETWORK_MODE_LTE_M_NBIOT=y

# MQTT
# STEP 2.1 - Enable and configure the MQTT library
CONFIG_MQTT_LIB=y
CONFIG_MQTT_CLEAN_SESSION=y

# Application
CONFIG_MQTT_PUB_TOPIC="devices/example-device/telemetry"
CONFIG_MQTT_PUB_TOPIC1="devices/example-device/location"
CONFIG_MQTT_BROKER_HOSTNAME="mqtt.example.com"
CONFIG_MQTT_BROKER_PORT=1883

CONFIG_GNSS_ERASE="ERASE"
CONFIG_BOARD_RESET="RESET"

#i2c configuration
CONFIG_I2C=y            # i2c function add
CONFIG_I2C_NRFX=y

CONFIG_NRFX_TWIM0=n
CONFIG_NRFX_TWIM1=n
CONFIG_NRFX_TWIM2=y
CONFIG_NRFX_TWIM3=y


CONFIG_PRINTK=y      
CONFIG_CONSOLE=y          
CONFIG_UART_CONSOLE=y 
CONFIG_SERIAL=y           
CONFIG_SENSOR=y


CONFIG_ASSERT=y
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_LOG_MODE_IMMEDIATE=y


CONFIG_CBPRINTF_FP_SUPPORT=y   # float %f 
CONFIG_MQTT_KEEPALIVE=120

CONFIG_MQTT_MESSAGE_BUFFER_SIZE=1024

CONFIG_NET_IPV4=y

#GNSS
CONFIG_LTE_NETWORK_MODE_LTE_M_NBIOT_GPS=y
CONFIG_MODEM_ANTENNA_GNSS_EXTERNAL=n
CONFIG_FPU=y

CONFIG_MODEM_ANTENNA=y
CONFIG_MODEM_ANTENNA_AT_COEX0="AT%XCOEX0=1,1,1570,1580"


#Watchdog
CONFIG_WATCHDOG=y


CONFIG_HWINFO=y


#PSM
CONFIG_LTE_PSM_REQ=y
CONFIG_LTE_LC_PSM_MODULE=y

CONFIG_LTE_LC_EDRX_MODULE=y
CONFIG_LTE_EDRX_REQ=y

#datetime
CONFIG_DATE_TIME=y
CONFIG_DATE_TIME_MODEM=y
CONFIG_DATE_TIME_AUTO_UPDATE=y
CONFIG_DATE_TIME_NTP=y



CONFIG_COUNTER=y


#ADC
CONFIG_ADC=y

#SPI
CONFIG_SPI=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_SPI_NOR=y
CONFIG_FLASH_PAGE_LAYOUT=y

#TFM silent log
CONFIG_TFM_LOG_LEVEL_SILENCE=y


CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=2048


CONFIG_REBOOT=y

CONFIG_GNSS_PERIODIC_TIMEOUT=780



CONFIG_NEWLIB_LIBC_NANO=n
